[package]
name = "ai_integration"
version = "0.1.0"
edition = "2021"

[dependencies]
criterion = "0.5.1"
image = "0.24.8"
tract = "0.21.0"
tract-onnx = "0.21.0"

[[bench]]
name = "tract"
harness = false
